// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHc9FUw6Yg8n1GRJdyAhsFmqKtym1-uvs',
    appId: '1:733301080431:web:db9e5fc9bd37fc5d06689a',
    messagingSenderId: '733301080431',
    projectId: 'newproject-9affb',
    authDomain: 'newproject-9affb.firebaseapp.com',
    storageBucket: 'newproject-9affb.appspot.com',
    measurementId: 'G-RB0BFY9EWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnnqJLKs3dfKNRTBrmGIgLHVznwmkUwvc',
    appId: '1:733301080431:android:7e43fe94967a88b606689a',
    messagingSenderId: '733301080431',
    projectId: 'newproject-9affb',
    storageBucket: 'newproject-9affb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpLU3TL54BHyLe1xtZ9bJsWWQn0f0wnk',
    appId: '1:733301080431:ios:244f361143b323b206689a',
    messagingSenderId: '733301080431',
    projectId: 'newproject-9affb',
    storageBucket: 'newproject-9affb.appspot.com',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtpLU3TL54BHyLe1xtZ9bJsWWQn0f0wnk',
    appId: '1:733301080431:ios:83d0c8532795dd6e06689a',
    messagingSenderId: '733301080431',
    projectId: 'newproject-9affb',
    storageBucket: 'newproject-9affb.appspot.com',
    iosBundleId: 'com.example.demoproject.RunnerTests',
  );
}
